// This file was generated by Prisma, and assumes you have installed the following:
// Configuração do Prisma: usa DIRECT_URL em migrations e DATABASE_URL como alternativa.
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
